import type {
  VocabularySection,
  VocabularyWord,
} from "~/features/vocabulary/model/types";

const VOCABULARY_IMAGE_BASE_PATH = "/images/vocabulary/en";

function verb(
  id: string,
  term: string,
  translation: string,
  sections: VocabularySection[],
  imageUrl = "",
  imageAlt = "",
): VocabularyWord {
  return {
    id,
    term,
    translation,
    type: "verb",
    sections,
    imageUrl,
    imageAlt,
  };
}

function other(
  id: string,
  term: string,
  translation: string,
  imageUrl = "",
  imageAlt = "",
): VocabularyWord {
  return {
    id,
    term,
    translation,
    type: "other",
    sections: ["other_words"],
    imageUrl,
    imageAlt,
  };
}

const EN_VERB_BANK: VocabularyWord[] = [
  verb(
    "en-verb-do",
    "do / does / did / done / doing",
    "Формы do: do/does/did/done/doing. Вспомогательный и смысловой глагол.",
    ["action_verbs", "modal_auxiliary_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/do.jpg`,
  ),
  verb(
    "en-verb-be",
    "be",
    "Быть (am/is/are/was/were/been/being).",
    ["state_verbs", "modal_auxiliary_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/be.jpg`,
  ),
  verb(
    "en-verb-have",
    "have",
    "Иметь (have/has/had), также вспомогательный глагол.",
    ["state_verbs", "modal_auxiliary_verbs"],
     `${VOCABULARY_IMAGE_BASE_PATH}/have.jpg`,
  ),
  verb("en-verb-know", "know", "знать", [
    "state_verbs",
    "thinking_decision_verbs",
  ],
    `${VOCABULARY_IMAGE_BASE_PATH}/know.jpg`,
  ),
  verb("en-verb-think", "think", "думать", [
    "state_verbs",
    "thinking_decision_verbs",
  ],
    `${VOCABULARY_IMAGE_BASE_PATH}/think.jpg`,
  ),
  verb("en-verb-understand", "understand", "понимать", ["state_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/understand.jpg`,
  ),
  verb("en-verb-want", "want", "хотеть", ["state_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/want.jpg`,
  ),
  verb("en-verb-need", "need", "нуждаться / нужно", ["state_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/need.jpg`,
  ),
  verb("en-verb-like", "like", "нравиться / любить", ["state_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/like.jpg`,
  ),
  verb("en-verb-love", "love", "любить", ["state_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/love.jpg`,
  ),
  verb("en-verb-hate", "hate", "ненавидеть", ["state_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/hate.jpg`,
  ),
  verb("en-verb-believe", "believe", "верить", ["state_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/believe.jpg`,
  ),
  verb("en-verb-remember", "remember", "помнить", ["state_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/remember.jpg`,
  ),
  verb("en-verb-forget", "forget", "забывать", ["state_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/forget.jpg`,
  ),
  verb("en-verb-seem", "seem", "казаться", ["state_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/seem.jpg`,
  ),
  verb("en-verb-feel", "feel", "чувствовать", ["state_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/feel.jpg`,
  ),

  verb("en-verb-make", "make", "делать / создавать", ["action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/make.jpg`,
  ),
  verb("en-verb-get", "get", "получать", ["action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/get.jpg`,
  ),
  verb("en-verb-give", "give", "давать", ["action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/give.jpg`,
  ),
  verb("en-verb-take", "take", "брать", ["action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/take.jpg`,
  ),
  verb("en-verb-put", "put", "класть / ставить", ["action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/put.jpg`,
  ),
  verb("en-verb-come", "come", "приходить", ["action_verbs", "movement_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/come.jpg`,
  ),
  verb("en-verb-go", "go", "идти / ехать", ["action_verbs", "movement_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/go.jpg`,
  ),
  verb("en-verb-see", "see", "видеть", ["action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/see.jpg`,
  ),
  verb("en-verb-look", "look", "смотреть", ["action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/look.jpg`,
  ),
  verb("en-verb-use", "use", "использовать", ["action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/use.jpg`,
  ),
  verb("en-verb-try", "try", "пытаться", ["action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/try.jpg`,
  ),
  verb("en-verb-call", "call", "звонить / называть", ["action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/call.jpg`,
  ),
  verb("en-verb-ask", "ask", "спрашивать", [
    "action_verbs",
    "communication_verbs",
  ],
    `${VOCABULARY_IMAGE_BASE_PATH}/ask.jpg`,
  ),
  verb("en-verb-help", "help", "помогать", ["action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/help.jpg`,
  ),

  verb("en-verb-walk", "walk", "ходить пешком", ["movement_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/walk.jpg`,
  ),
  verb("en-verb-run", "run", "бежать", ["movement_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/run.jpg`,
  ),
  verb("en-verb-move", "move", "двигаться", ["movement_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/move.jpg`,
  ),
  verb("en-verb-leave", "leave", "уходить / покидать", ["movement_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/leave.jpg`,
  ),
  verb("en-verb-arrive", "arrive", "прибывать", ["movement_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/arrive.jpg`,
  ),
  verb("en-verb-enter", "enter", "входить", ["movement_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/enter.jpg`,
  ),
  verb("en-verb-travel", "travel", "путешествовать", ["movement_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/travel.jpg`,
  ),
  verb("en-verb-bring", "bring", "приносить", ["movement_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/bring.jpg`,
  ),
  verb("en-verb-carry", "carry", "нести", ["movement_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/carry.jpg`,
  ),
  verb("en-verb-drive", "drive", "водить машину", ["movement_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/drive.jpg`,
  ),
  verb("en-verb-fly", "fly", "летать", ["movement_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/fly.jpg`,
  ),

  verb("en-verb-say", "say", "говорить", ["communication_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/say.jpg`,
  ),
  verb("en-verb-tell", "tell", "рассказывать / сообщать", [
    "communication_verbs",
  ],
    `${VOCABULARY_IMAGE_BASE_PATH}/tell.jpg`,
  ),
  verb("en-verb-speak", "speak", "говорить", ["communication_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/speak.jpg`,
  ),
  verb("en-verb-talk", "talk", "разговаривать", ["communication_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/talk.jpg`,
  ),
  verb("en-verb-answer", "answer", "отвечать", ["communication_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/answer.jpg`,
  ),
  verb("en-verb-explain", "explain", "объяснять", ["communication_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/explain.jpg`,
  ),
  verb("en-verb-discuss", "discuss", "обсуждать", ["communication_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/discuss.jpg`,
  ),
  verb("en-verb-show", "show", "показывать", ["communication_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/show.jpg`,
  ),
  verb("en-verb-teach", "teach", "учить (кого-то)", ["communication_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/teach.jpg`,
  ),
  verb("en-verb-learn", "learn", "учиться", ["communication_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/learn.jpg`,
  ),

  verb("en-verb-decide", "decide", "решать", ["thinking_decision_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/decide.jpg`,
  ),
  verb("en-verb-choose", "choose", "выбирать", ["thinking_decision_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/choose.jpg`,
  ),
  verb("en-verb-plan", "plan", "планировать", ["thinking_decision_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/plan.jpg`,
  ),
  verb("en-verb-mean", "mean", "значить", ["thinking_decision_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/mean.jpg`,
  ),
  verb("en-verb-consider", "consider", "рассматривать / учитывать", [
    "thinking_decision_verbs",
  ],
    `${VOCABULARY_IMAGE_BASE_PATH}/consider.jpg`,
  ),
  verb("en-verb-expect", "expect", "ожидать", ["thinking_decision_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/expect.jpg`,
  ),
  verb("en-verb-hope", "hope", "надеяться", ["thinking_decision_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/hope.jpg`,
  ),
  verb("en-verb-guess", "guess", "догадываться", ["thinking_decision_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/guess.jpg`,
  ),
  verb("en-verb-agree", "agree", "соглашаться", ["thinking_decision_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/agree.jpg`,
  ),

  verb("en-verb-can", "can", "мочь / уметь", ["modal_auxiliary_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/can.jpg`,
  ),
  verb("en-verb-could", "could", "мог / мог бы", ["modal_auxiliary_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/could.jpg`,
  ),
  verb("en-verb-may", "may", "мочь (разрешение/вероятность)", [
    "modal_auxiliary_verbs",
  ],
    `${VOCABULARY_IMAGE_BASE_PATH}/may.jpg`,
  ),
  verb("en-verb-might", "might", "мог бы / возможно", [
    "modal_auxiliary_verbs",
  ],
    `${VOCABULARY_IMAGE_BASE_PATH}/might.jpg`,
  ),
  verb("en-verb-must", "must", "должен", ["modal_auxiliary_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/must.jpg`,
  ),
  verb("en-verb-should", "should", "следует", ["modal_auxiliary_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/should.jpg`,
  ),
  verb("en-verb-will", "will", "будущее время / воля", [
    "modal_auxiliary_verbs",
  ],
    `${VOCABULARY_IMAGE_BASE_PATH}/will.jpg`,
  ),
  verb("en-verb-would", "would", "бы / вежливая форма will", [
    "modal_auxiliary_verbs",
  ],
    `${VOCABULARY_IMAGE_BASE_PATH}/would.jpg`,
  ),
  verb("en-verb-shall", "shall", "должен / будем (формально)", [
    "modal_auxiliary_verbs",
  ],
    `${VOCABULARY_IMAGE_BASE_PATH}/shall.jpg`,
  ),

  verb("en-verb-start", "start", "начинать", ["action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/start.jpg`,
  ),
  verb("en-verb-finish", "finish", "заканчивать", ["action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/finish.jpg`,
  ),
  verb("en-verb-work", "work", "работать", ["action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/work.jpg`,
  ),
  verb("en-verb-live", "live", "жить", ["state_verbs", "action_verbs"],
    `${VOCABULARY_IMAGE_BASE_PATH}/live.jpg`,
  ),
];

const EN_OTHER_WORD_BANK: VocabularyWord[] = [
  other("en-other-him", "him", "его, ему"),
  other("en-other-these", "these", "эти"),
  other("en-other-this", "this", "этот"),
  other(
    "en-other-i-like-you",
    "I like you",
    "Ты мне нравишься (подлежащее — «я»).",
  ),
  other("en-other-she", "she", "она"),
  other("en-other-what", "what", "Что? / Какой?"),
  other("en-other-that", "that", "тот"),
  other("en-other-who", "who", "Кто?"),
  other("en-other-when", "when", "Когда?"),
  other("en-other-he", "he", "он"),
  other("en-other-not", "not", "Отрицательная частица not."),
  other("en-other-there", "there", "там / туда"),
  other("en-other-no-i-can-t", "No, I can't", "Нет."),
  other("en-other-we", "we", "мы"),
  other("en-other-here", "here", "здесь / сюда"),
  other("en-other-they", "they", "они"),
  other("en-other-it", "it", "оно/это"),
  other("en-other-why", "why", "Почему? / Зачем?"),
  other("en-other-them", "them", "их, им"),
  other("en-other-those", "those", "те"),
  other("en-other-us", "us", "нас, нам"),
  other("en-other-her", "her", "её, ей"),
  other("en-other-me", "me", "меня, мне"),
  other("en-other-where", "where", "Где? / Куда?"),
  other("en-other-you", "you", "вы, ты"),
  other("en-other-i", "I", "Я"),
  other("en-other-how-many", "how many", "сколько"),
  other("en-other-yes-i-do", "Yes, I do", "Да."),
  other("en-other-i-need-to-go", "I need to go", "Мне нужно идти."),
  other("en-other-how", "how", "Как? / Каким образом?"),
];

export const EN_WORD_BANK: VocabularyWord[] = [
  ...EN_VERB_BANK,
  ...EN_OTHER_WORD_BANK,
];
